<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/7/23 0023
 * Time: 10:53
 */

namespace app\controllers;


use yii\web\Controller;
use Yii;

class BaseController extends Controller
{
    public $layout = "chain";
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest && Yii::$app->controller->id != 'login') {
            return $this->redirect("/login/index");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}