<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/7/23 0023
 * Time: 10:53
 */

namespace app\controllers;


use app\models\User;
use yii\web\Controller;
use Yii;
use app\models\Role;

class BaseController extends Controller
{
    public $layout = "chain";
    protected $auth;
    protected $user;
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            if(Yii::$app->controller->id != 'login') return $this->redirect("/login/index");
        }else{
            $this->user = User::findIdentity(Yii::$app->user->getId());
            $this->getAuth();

            $this->view->params['user'] = $this->user;
            $this->view->params['auth'] = $this->auth;

            if(!$this->checkAccess()){
                return $this->redirect("/login/index");
            }

            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        }
    }

    /**
     * 获取权限数组
     */
    protected function getAuth(){
        if($this->user->isSuperman()){
            $this->auth = Yii::$app->params['auth'];
        }else{
            $auth = [];
            $roles = [];
            $config = $this->user->config; //角色配置信息
            if($config){
                $config = json_decode($config,true);
                foreach ($config as $id) {
                    $role = Role::getEnableRoleById($id);
                    if($role && $role->config){
                        $p = json_decode($role->config,true);
                        $roles = array_merge($roles, $p);
                    }
                }
            }
            if($roles){
                foreach ( Yii::$app->params['auth'] as $k=>$v){
                    if($roles[$k]['all']){
                        $auth[$k] = $v;
                    }elseif (Yii::$app->params['auth'][$k]['action']){
                        $auth[$k]['info'] = Yii::$app->params['auth'][$k]['info'];
                        $auth[$k]['defaultUrl'] = Yii::$app->params['auth'][$k]['defaultUrl'];
                        foreach (Yii::$app->params['auth'][$k]['action'] as $kk=>$vv){
                            if($roles[$k]['action'][$kk]) $auth[$k]['action'][$kk] = $vv;
                        }
                    }
                }
            }
            $this->auth = $auth;
        }
    }


    /**
     * 查看权限
     */

    protected function checkAccess(){
        if($this->user->isSuperman()){
            return true;
        }else{
            if($this->auth[Yii::$app->controller->id]['all']){
                return true;
            }
            if($this->auth[Yii::$app->controller->id]['action'][Yii::$app->controller->action->id]){
                return true;
            }

            if(Yii::$app->controller->action->id == "upload"){
                return true;
            }

            if(Yii::$app->controller->id=="index" && Yii::$app->controller->action->id=="index"){
                return true;//修复循环重定向bug
            }
            return false;
        }
    }

    public function actions()
    {
        return [
            'upload' => [
                'class' => 'kucha\ueditor\UEditorAction',
            ]
        ];
    }

}