<?php

return [
    'adminEmail' => 'admin@example.com',
    'auth'=>[
        /*
        'login'=>[
            "info"=>"登录",
            "hide"=>true,
            'defaultUrl'=>'login/index',
            "action"=>[
                "all"=>"全部授权"
            ]
        ],
        */
        "user"=>[
            "all"=>"全部授权",
            "info"=>"用户管理",
            'defaultUrl'=>'user/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建用户",
                "view"=>"查看详情",
                "update"=>"修改用户",
                "delete"=>"删除用户"
            ]
        ],
        "role"=>[
            "all"=>"全部授权",
            "info"=>"角色管理",
            'defaultUrl'=>'role/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建角色",
                "view"=>"查看详情",
                "update"=>"修改角色",
                "delete"=>"删除角色"
            ]
        ],
        "resource"=>[
            "all"=>"全部授权",
            "info"=>"资源管理",
            'defaultUrl'=>'resource/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建资源",
                "view"=>"查看详情",
                "update"=>"修改资源",
                "delete"=>"删除资源"
            ]
        ],
    ]
];
