<?php

return [
    'adminEmail' => 'admin@example.com',
    'auth'=>[
        /*
        'login'=>[
            "info"=>"登录",
            "hide"=>true,
            'defaultUrl'=>'login/index',
            "action"=>[
                "all"=>"全部授权"
            ]
        ],
        */
        "user"=>[
            "all"=>"全部授权",
            "info"=>"用户管理",
            'defaultUrl'=>'user/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建用户",
                "view"=>"查看详情",
                "update"=>"修改用户",
                "delete"=>"删除用户"
            ]
        ],
        "role"=>[
            "all"=>"全部授权",
            "info"=>"角色管理",
            'defaultUrl'=>'role/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建角色",
                "view"=>"查看详情",
                "update"=>"修改角色",
                "delete"=>"删除角色"
            ]
        ],
        "resource"=>[
            "all"=>"全部授权",
            "info"=>"资源管理",
            'defaultUrl'=>'resource/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建资源",
                "view"=>"查看详情",
                "update"=>"修改资源",
                "delete"=>"删除资源"
            ]
        ],
        "feedback"=>[
            "all"=>"全部授权",
            "info"=>"留言管理",
            'defaultUrl'=>'feedback/index',
            "action"=>[
                "index"=>"查看列表",
                "view"=>"查看详情",
                "update"=>"回复留言",
                "delete"=>"删除留言"
            ]
        ],
        "cls"=>[
            "all"=>"全部授权",
            "info"=>"课程管理",
            'defaultUrl'=>'cls/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建课程",
                "view"=>"查看详情",
                "update"=>"更新课程",
                "delete"=>"删除课程"
            ]
        ],
        "good-student"=>[
            "all"=>"全部授权",
            "info"=>"优秀学员管理",
            'defaultUrl'=>'good-student/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建优秀学员信息",
                "view"=>"查看详情",
                "update"=>"更新优秀学员信息",
                "delete"=>"删除优秀学员信息"
            ]
        ],
        "info"=>[
            "all"=>"全部授权",
            "info"=>"资讯管理",
            'defaultUrl'=>'info/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建资讯",
                "view"=>"查看详情",
                "update"=>"更新资讯",
                "delete"=>"删除资讯"
            ]
        ],
        "photo"=>[
            "all"=>"全部授权",
            "info"=>"剧照管理",
            'defaultUrl'=>'photo/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建剧照",
                "view"=>"查看详情",
                "update"=>"更新剧照",
                "delete"=>"删除剧照"
            ]
        ],
        "teacher"=>[
            "all"=>"全部授权",
            "info"=>"教师管理",
            'defaultUrl'=>'teacher/index',
            "action"=>[
                "index"=>"查看列表",
                "create"=>"创建教师",
                "view"=>"查看详情",
                "update"=>"更新教师",
                "delete"=>"删除教师"
            ]
        ],
    ]
];
