<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%feedback}}".
 *
 * @property integer $id
 * @property integer $stu_id
 * @property string $message
 * @property integer $enable
 * @property integer $reply_type
 * @property string $reply
 * @property string $created_time
 * @property string $updated_time
 * @property integer $uid
 */
class Feedback extends \yii\db\ActiveRecord
{
    const ENABLE = 1;
    const DISABLE = 0;

    const REPLY_SMS = 1;
    const REPLY_MSG = 2;
    const REPLY_NO = 0;//未回复

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%feedback}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['stu_id', 'message'], 'required'],
            [['stu_id', 'enable', 'reply_type', 'uid'], 'integer'],
            [['message', 'reply'], 'string'],
            [['created_time', 'updated_time'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'stu_id' => '学生id',
            'message' => '留言内容',
            'enable' => '状态',
            'reply_type' => '回复类型',
            'reply' => '回复内容',
            'created_time' => '创建时间',
            'updated_time' => '最后修改时间',
            'uid' => '管理员id',
        ];
    }

    public function behaviors()
    {
        return [
            "timestamp"=> [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['created_time','updated_time'],
                    \yii\db\ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_time'],
                ],
                'value' => function() { return date('Y-m-d H:i:s');}
            ],
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $user = Yii::$app->user->getIdentity();
            $this->uid = $user->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public static function getReplyTypeMap(){
        return [
            self::REPLY_NO=>'未回复',
            self::REPLY_MSG=>"短信回复",
            self::REPLY_SMS=>'在线回复'
        ];
    }

    public static function getEnableMap(){
        return [
            self::ENABLE => '有效',
            self::DISABLE=>'已删除'
        ];
    }

}
